CREATE TABLE IF NOT EXISTS person(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT);
INSERT or IGNORE INTO person VALUES (1, 'Sato');
INSERT or IGNORE INTO person VALUES (2, 'Goto');
INSERT or IGNORE INTO person VALUES (3, 'Kondo');
 